import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footter from './components/Footer'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ADC',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footter />
      </body>
    </html>
  )
}
