import { Inter } from "next/font/google"

import "./globals.css"

import ContextProvider from "../../context"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { defaultLocale } from "@/navigation"

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "ADC",
  description: "Generated by create next app",
}

export default function RootLayout({ children, params }) {
  return (
    <html lang={params?.locale || defaultLocale}>
      <body>
        <ContextProvider>
          <Navbar lang={params?.lang} />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  )
}
